### PR TITLE
Resolve insufficient funding

### LINKED ISSUE #18: Recover funds after failed funding
Currently, the Pallet does not allow to recover funds from an unfunded channel. A dispute conclusion will just fail in this case.

https://github.com/perun-network/perun-polkadot-pallet/blob/b5a1897cdf5c7755cddfb2b1841331acab349aba/src/lib.rs#L466

We need to revise the Pallet so that we payout the initial deposits in case of an underfunded channel.

### PR DESCRIPTION
**Pull request by matthiasgeihs**
Closes #18

### CODE REVIEW

File: tests/conclude.rs [hunk 1]
```diff
@@ -215,15 +215,19 @@ fn conclude_insufficient_deposits() {
...
+		let bob_deposits = Perun::deposits(setup.fids.bob);
+		assert_ok!(Perun::conclude_final(
+			Origin::signed(setup.ids.alice),
+			setup.params.clone(),
+			state.clone(),
+			sigs
+		));
+		assert_event_concluded(state.channel_id);
+
+		// Holdings did not changed
```
Comment (RmbRT) [inline tests/conclude.rs:228]:
```suggestion
		// Holdings did not change
```

**Review by RmbRT — CHANGES_REQUESTED** [review]
ok

**Review by RmbRT — APPROVED** [review]
